# Generated by Django 3.1.2 on 2020-12-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0003_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
