# Generated by Django 3.1.2 on 2020-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0008_auto_20201207_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_validate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
