# Generated by Django 3.1.2 on 2020-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0011_pet_pet_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_intact',
            field=models.BooleanField(default=False),
        ),
    ]
