# Generated by Django 3.1.2 on 2020-12-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0013_auto_20201208_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_intact',
        ),
    ]
