# Generated by Django 3.1.2 on 2020-12-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0015_auto_20201208_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_rate',
            field=models.FloatField(),
        ),
    ]
