# Generated by Django 3.1.2 on 2020-12-13 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0018_pet_diary_pet_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_diary',
            name='pet_entry',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_diary',
            name='user_entry',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
