# Generated by Django 3.1.2 on 2020-12-14 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_PackTrack', '0019_auto_20201213_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_diary',
            name='owner',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='pet_owners', to='App_PackTrack.pet'),
            preserve_default=False,
        ),
    ]
